# Define enumerations using the enum base class

from enum import Enum, unique, auto


class Fruit(Enum):
    APPLE = 1
    BANANA = 2
    ORANGE = 3
    TOMATO = 4
    PEAR = auto()


def main():
    pass
    # TODO: enums have human-readable values and types
    print(Fruit.APPLE)
    print(type(Fruit.APPLE))
    print(repr(Fruit.APPLE))

    # TODO: enums have name and value properties
    print(Fruit.APPLE.name, Fruit.APPLE.value)

    # TODO: print the autogenerated value
    print(Fruit.PEAR.value)

    # TODO:enums are hashable - can be used as keys
    myFruits = {}
    myFruits[Fruit.BANANA] = "OOGA OGGA "
    print(myFruits[Fruit.BANANA])


if __name__ == "__main__":
    main()
